default:
  agen_com_dict: 'agency_communion.dic'
  general_inquir: 'inquirer.dic'
  prosocial_dict: 'prosocial.dic'
  stress_dict: 'Stress_dictionary.dic'
  tms_streng_dict: 'sj-dic-2-sgr-10.1177_10464964231182130.dic'
  uncertainty_dict: 'Uncertainty_Business.dic'
  personal_values_dict: 'personal_values.dic'
  wwpb_wellbeing: 'wwbp_wellbeing.csv'
calculon:
  db_name: 'nar_clim'
  dbUser: 'postgres'
  dbPW: 'LetMeIn21'
  db_host: '192.168.7.212'
  dbPort: 5424
  nrc_data_path: '/Volumes/calculon/event_reporting/nrc'
  asrs_data_path: '/Volumes/calculon/event_reporting/aviation/ASRS_data'
  rail_data_path: '/Volumes/calculon/event_reporting/rail_safety_reports'
  phmsa_data_path: '/Volumes/calculon/event_reporting/phmsa'